---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-devops-mysql
  name: mysql
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-devops-mysql
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-devops-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: mysql-secrets
              optional: false
        image: mysql:5.6
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql-port
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-storage
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-storage
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: mysql
  namespace: devops
spec:
  ports:
  - name: mysql-port
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    workload.user.cattle.io/workloadselector: deployment-devops-mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-devops-wordpress
  name: wordpress
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-devops-wordpress
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-devops-wordpress
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: mysql-secrets
              optional: false
        image: wordpress:4.8-apache
        imagePullPolicy: Always
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress
          protocol: TCP 
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-storage 
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-storage
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: wordpress-nodeport
  namespace: devops
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: wordpress
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-devops-wordpress
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    cattle.io/creator: norman
  name: wordpress
  namespace: devops
spec:
  rules:
  - host: wordpress.devops.35.247.229.217.nip.io
    http:
      paths:
      - backend:
          serviceName: wordpress-nodeport
          servicePort: 80
